# Generated by Django 4.2.6 on 2023-11-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientstable',
            options={'verbose_name': 'ingerdient table', 'verbose_name_plural': 'ingredient tables'},
        ),
        migrations.AlterField(
            model_name='ingredientstable',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='', related_name='ingredient_table', to='recipes.recipe'),
        ),
    ]
