# Generated by Django 4.2.6 on 2023-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='IngredientsTable',
        ),
        migrations.AlterModelOptions(
            name='ingredientstable',
            options={'verbose_name': 'IngredientsTable'},
        ),
    ]
