# Generated by Django 4.2.6 on 2023-11-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredients_ingredientstable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstable',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
    ]
