# Generated by Django 4.2.6 on 2023-12-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='recipe',
        ),
    ]
