# Generated by Django 4.2.6 on 2023-12-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredients_ingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
